# Alpaca Configuration for Qlib Production Trading
broker:
  type: "alpaca"
  api_key: "${ALPACA_API_KEY}"
  secret_key: "${ALPACA_SECRET_KEY}"
  paper_trading: true
  alpaca_base_url: "https://paper-api.alpaca.markets"
  host: ""  # Not used for Alpaca
  port: 0   # Not used for Alpaca
  client_id: 1

risk:
  max_position_size: 100000
  max_daily_loss: 5000
  max_sector_exposure: 0.3
  max_single_stock_exposure: 0.1
  max_leverage: 1.0
  stop_loss_pct: 0.05
  position_sizing_method: "kelly"

data:
  data_provider: "alpaca"
  api_key: "${ALPACA_API_KEY}"
  base_url: "https://paper-api.alpaca.markets"
  update_frequency: "1min"
  cache_duration: 300

trading:
  trading_hours:
    start: "09:30"
    end: "16:00"
  default_order_type: "market"
  max_slippage: 0.001
  min_order_size: 100
  max_order_size: 10000
  execution_delay: 0.1
  retry_failed_orders: true
  max_order_retries: 3
  symbols: ["AAPL", "GOOGL", "MSFT", "SPY", "QQQ"]
  enable_trading: false  # Set to true for live trading
  max_position_size: 0.1         # 10% of account per position (as a fraction)
  max_positions: 10              # Max number of open positions
  min_cash_reserve: 0.1          # 10% of account kept in cash
  max_daily_loss: 0.05           # 5% daily loss limit
  stop_loss_pct: 0.05            # 5% stop loss
  take_profit_pct: 0.1           # 10% take profit

monitoring:
  alert_email: null
  slack_webhook: null
  log_level: "INFO"
  performance_metrics: true
  risk_alerts: true
  trade_logging: true 