# Alpaca Configuration for Qlib Production Trading
broker:
  broker_type: "alpaca"
  host: ""  # Not used for Alpaca
  port: 0   # Not used for Alpaca
  client_id: 1
  api_key: "${ALPACA_API_KEY}"  # Set via environment variable
  api_secret: "${ALPACA_SECRET_KEY}"  # Set via environment variable
  paper_trading: true
  alpaca_base_url: "https://paper-api.alpaca.markets"

risk:
  max_position_size: 100000
  max_daily_loss: 5000
  max_sector_exposure: 0.3
  max_single_stock_exposure: 0.1
  max_leverage: 1.0
  stop_loss_pct: 0.05
  position_sizing_method: "kelly"

data:
  data_provider: "alpaca"
  api_key: "${ALPACA_API_KEY}"
  base_url: "https://paper-api.alpaca.markets"
  update_frequency: "1min"
  cache_duration: 300

trading:
  default_order_type: "market"
  max_slippage: 0.001
  min_order_size: 100
  max_order_size: 10000
  execution_delay: 0.1
  retry_failed_orders: true
  max_order_retries: 3
  symbols: ["AAPL", "GOOGL", "MSFT", "SPY", "QQQ"]
  enable_trading: false  # Set to true for live trading

monitoring:
  alert_email: null
  slack_webhook: null
  log_level: "INFO"
  performance_metrics: true
  risk_alerts: true
  trade_logging: true 